server.port = 8084
spring.application.name=markers
spring.profiles.active=dev



spring.main.banner-mode=off
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.datasource.username=admin
spring.datasource.password=Jimmy970126*
spring.datasource.url=jdbc:mysql://database-coordinadora.cizyoqwa8ouu.us-east-1.rds.amazonaws.com:3306/markers
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.poolName=HikariPoolBooks
